### ISSUE TITLE
Does not run on Python 3.7.3

### ISSUE THREAD

**Issue by romanrm** [twisteroidambassador/async_stagger#5]
Hello,

I see in the docs: "async_stagger requires Python 3.6 or later. ... It does not have any external dependencies."

But on Python 3.7.3 I get an error:
```
Traceback (most recent call last):
  File "prettysocks.py", line 34, in <module>
    from typing import Callable, Awaitable, Tuple, Union
  File "/tmp/prettysocks/typing.py", line 3, in <module>
    from typing import Tuple, Union
ImportError: cannot import name 'Tuple' from 'typing' (/tmp/prettysocks/typing.py)
```
What am I missing?

Note that I did not "pip install" the package, instead I copied all the async_stagger files directly into the same folder as prettysocks, and launch the latter.

**Comment by twisteroidambassador** [comment]
Don't put files inside `async_stagger` directory alongside `prettysocks.py`. Instead, put the `async_stagger` directory next to `prettysocks.py`.

`typing` is part of Python's standard library. When there's a "loose" `typing.py` next to `prettysocks.py` it imports the wrong thing.

**Comment by romanrm** [comment]
Thanks!
